version: '3.4'

services:
  restapi:
    image: restapi
    build: .
    command: npm start  
    environment:
      NODE_ENV: production
    ports:
      - 3030:3030
    volumes: 
      - .:/usr/src/app 
