version: '3.4'

services:
  restapi:
    image: restapi
    build:
      context: REST_API
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3030:3030
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "app.js"]
